#!/bin/bash
# 肆方自架版入口：env → install.config → install.sh（起 pg/redis/pm2）→ 搬運器 → 常駐
set -e
cat > /app/install.config <<CFG
DISCORD_BOT_TOKEN=${CRAIG_BOT_TOKEN}
DISCORD_APP_ID=${CRAIG_APP_ID}
CLIENT_ID=${CRAIG_APP_ID}
CLIENT_SECRET=${CRAIG_CLIENT_SECRET}
DEVELOPMENT_GUILD_ID=${CRAIG_GUILD_ID}
PATREON_CLIENT_ID=test
PATREON_CLIENT_SECRET=test
PATRON_TIER_MAP={\"00001\":2,\"0002\":3}
PATREON_WEBHOOK_SECRET=test
GOOGLE_CLIENT_ID=test
GOOGLE_CLIENT_SECRET=test
MICROSOFT_CLIENT_ID=test
MICROSOFT_CLIENT_SECRET=test
DROPBOX_CLIENT_ID=test
DROPBOX_CLIENT_SECRET=test
APP_URI=http://localhost:3000
JWT_SECRET=${CRAIG_JWT_SECRET:-sifang-jwt}
API_PORT=5029
API_HOST=0.0.0.0
API_HOMEPAGE=${CRAIG_PUBLIC_URL:-http://localhost:5029}
ENNUIZEL_BASE=https://ez.craig.horse/
TRUST_PROXY=true
SENTRY_SAMPLE_RATE=1.0
SENTRY_SAMPLE_RATE_API=1.0
SERVER_NAME=sifang
REDIS_HOST=
REDIS_PORT=
NODE_VERSION="18.18.2"
DATABASE_NAME="craig"
POSTGRESQL_USER="craig"
POSTGRESQL_PASSWORD="craig"
POSTGRESQL_START_TIMEOUT_S=30
REDIS_START_TIMEOUT_S=30
DATABASE_URL=\"postgresql://craig:craig@localhost:5432/craig?schema=public\"
CFG
/app/install.sh
python3 /app/relay.py &
sleep infinity
